server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:db/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/kitchen-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          waiter-service:
            url: http://localhost:8081

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kitchen-group
      auto-offset-reset: earliest