server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:db/master.xml

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      isolation-level: read_committed
      properties:
        spring:
          json:
            trusted:
              packages: '*'




  datasource:
    url: jdbc:postgresql://localhost:5432/kitchen-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          waiter-service:
            url: http://localhost:8081

kafka:
  topic:
    name:
      createOrderTopic
    partitions: 1
    replicas: 1



