<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.liga</groupId>
        <artifactId>liga-internship</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>dependency_bom</artifactId>
    <packaging>pom</packaging>


    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <spring.actuator.version>3.4.4</spring.actuator.version>
        <spring.web.version>3.4.4</spring.web.version>
        <lombok.version>1.18.36</lombok.version>
        <spring.devtools.version>3.4.4</spring.devtools.version>
        <jackson.datatype.jsr310.version>2.18.3</jackson.datatype.jsr310.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <logback.vesion>1.5.18</logback.vesion>
        <slf4j.version>2.0.16</slf4j.version>
        <mybatis.generator.plugin.version>1.4.2</mybatis.generator.plugin.version>
        <mybatis.itfsw.generator.plugin.version>1.4.6</mybatis.itfsw.generator.plugin.version>
        <mybatis.generate.version>1.4.3</mybatis.generate.version>
        <mybatis.core.version>3.5.19</mybatis.core.version>
        <mybatis.spring.boot.starter>3.0.4</mybatis.spring.boot.starter>
        <postgresql.version>42.7.5</postgresql.version>
        <liquibase.version>4.31.1</liquibase.version>
        <spring.boot.starter.validation.version>3.4.4</spring.boot.starter.validation.version>
        <jakarta.persistence.api.verson>3.1.0</jakarta.persistence.api.verson>
        <hibernate.jpamodelgen.version>6.6.4.Final</hibernate.jpamodelgen.version>
        <jakarta.xml.bind.version>4.0.2</jakarta.xml.bind.version>
        <jaxb.version>4.0.5</jaxb.version>
        <spring.cloud.starter.openfeign.version>4.2.0</spring.cloud.starter.openfeign.version>
        <spring.kafka.version>3.2.4</spring.kafka.version>
        <springdoc.openapi.starter.version>2.8.0</springdoc.openapi.starter.version>
        <!--        test-->
        <spring.boot.starter.test.version>3.2.10</spring.boot.starter.test.version>
        <postgres.testcontainers.version>1.20.6</postgres.testcontainers.version>
        <testcontainers.version>1.20.6</testcontainers.version>
        <testcontainers.junit.jupiterversion>1.20.6</testcontainers.junit.jupiterversion>
        <testcontainers.kafka.version>1.19.1</testcontainers.kafka.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>${spring.boot.starter.test.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-actuator</artifactId>
                <version>${spring.actuator.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring.web.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-validation</artifactId>
                <version>${spring.boot.starter.validation.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <optional>true</optional>
                <version>${lombok.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-devtools</artifactId>
                <version>${spring.devtools.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>${jackson.datatype.jsr310.version}</version>
            </dependency>

            <!--Mybatis-->
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter-test</artifactId>
                <version>${mybatis.spring.boot.starter}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${mybatis.spring.boot.starter}</version>
            </dependency>

            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
                <scope>runtime</scope>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>com.itfsw</groupId>
                <artifactId>mybatis-generator-plugin</artifactId>
                <version>${mybatis.itfsw.generator.plugin.version}</version>
            </dependency>

            <dependency>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-core</artifactId>
                <version>${liquibase.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>${jakarta.persistence.api.verson}</version>
            </dependency>

            <dependency>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-jpamodelgen</artifactId>
                <version>${hibernate.jpamodelgen.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>${jakarta.xml.bind.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${jaxb.version}</version>
            </dependency>

            <!--            feign-->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-openfeign</artifactId>
                <version>${spring.cloud.starter.openfeign.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.kafka</groupId>
                <artifactId>spring-kafka</artifactId>
                <version>${spring.kafka.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.openapi.starter.version}</version>
            </dependency>


            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgres.testcontainers.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${testcontainers.junit.jupiterversion}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>kafka</artifactId>
                <version>${testcontainers.kafka.version}</version>
                <scope>test</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.liquibase</groupId>
                    <artifactId>liquibase-maven-plugin</artifactId>
                    <version>${liquibase.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>


</project>