server:
  port: 8081

spring:
  liquibase:
    change-log: classpath:db/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5433/waiter-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          kitchen-service:
            url: http://localhost:8080

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml